=== F5Networks/f5-declarative-onboarding/src/schema/1.3.1/remote.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/schema/remote.schema.json",
    "title": "F5 Declarative Onboarding request declaration",
    "description": "Wrapper for remote onboarding of a BIG-IP device using F5 Declarative Onboarding",
    "type": "object",
    "required": ["class", "declaration"],
    "properties": {
        "class": {
            "description": "Indicates that this is a Declarative Onboarding request",
            "type": "string",
            "const": "DO"
        },
        "targetHost": {
            "description": "Hostname or IP address of ADC to which request applies (default localhost)",
            "type": "string",
            "anyOf": [
                { "format": "ipv4" },
                { "format": "ipv6" },
                { "format": "hostname" }
            ],
            "default": "localhost"
        },
        "targetPort": {
            "description": "TCP port number of management service on targetHost; default 0 means try common ports",
            "type": "integer",
            "minimum": 0,
            "maximum": 65535,
            "default": 0
        },
        "targetUsername": {
            "description": "Username of principal authorized to modify configuration of targetHost (may not include the character ':').  NOTE:  this is generally not required to configure 'localhost' because client authentication and authorization precede invocation of DO.  It is also not required for any targetHost if you populate targetTokens",
            "type": "string",
            "anyOf": [
                { "format": "json-pointer" },
                { "pattern": "^[^:]{0,254}$" }
            ]
        },
        "targetPassphrase": {
            "description": "Passphrase for targetUsername account.  This is generally not required to configure 'localhost' and is not required when you populate targetTokens",
            "type": "string",
            "anyOf": [
                { "format": "json-pointer" },
                { "pattern": "^.{0,254}$" }
            ]
        },
        "targetTokens": {
            "description": "One or more HTTP headers (each a property, like 'X-F5-Auth-Token': 'ABC123') you want to send with queries to the targetHost management service as authentication/authorization tokens",
            "oneOf": [
                {
                    "description": "Pointer to tokens in a format that matches the 'object' schema below",
                    "type": "string",
                    "anyOf": [
                        { "format": "json-pointer" }
                    ]
                },
                {
                    "type": "object",
                    "patternProperties": {
                        "^[^\\x00-\\x20:\\x7f-\\xff]{1,254}$": {
                            "type": "string",
                            "pattern": "^[^\\x00-\\x1f\\x7f-\\xff]{0,8192}$"
                        }
                    },
                    "additionalProperties": false
                }
            ]
        },
        "targetTimeout": {
            "description": "Maximum delay allowed while communicating with targetHost device (seconds, default 900)",
            "type": "integer",
            "minimum": 1,
            "maximum": 900,
            "default": 900
        },
        "declaration": {
            "description": "Declaration to deploy to targetHost",
            "$ref": "base.schema.json#"
        }
    },
    "additionalProperties": false
}

=== F5Networks/f5-declarative-onboarding/examples/licenseViaBigIqReachableASG.json
{
    "class": "DO",
    "targetHost": "192.0.2.4",
    "targetUsername": "/declaration/Credentials/1/bigiqUsername",
    "targetPassphrase": "/declaration/Credentials/1/password",
    "declaration": {
        "schemaVersion": "1.0.0",
        "class": "Device",
        "label": "Use App Services Gateway to license BIG-IP via BIG-IQ when BIG-IP is reachable from BIG-IQ",
        "Credentials": [
            {
                "username": "bigIqAdmin",
                "password": "foofoo"
            },
            {
                "username": "admin",
                "password": "asdfjkl"
            }
        ],
        "Common": {
            "class": "Tenant",
            "hostname": "bigip.example.com",
            "myLicense": {
                "class": "License",
                "licenseType": "licensePool",
                "bigIqHost": "192.0.2.200",
                "bigIqUsername": "/Credentials/0/bigiqUsername",
                "bigIqPassword": "/Credentials/0/password",
                "licensePool": "myUtilityLicense",
                "skuKeyword1": "key1",
                "skuKeyword2": "key2",
                "unitOfMeasure": "hourly",
                "reachable": true,
                "bigIpUsername": "/Credentials/1/bigipUsername",
                "bigIpPassword": "/Credentials/1/password"
            },
            "myDns": {
                "class": "DNS",
                "nameServers": [
                    "8.8.8.8",
                    "2001:4860:4860::8844"
                ],
                "search": [
                    "f5.com"
                ]
            },
            "myNtp": {
                "class": "NTP",
                "servers": [
                    "0.pool.ntp.org",
                    "1.pool.ntp.org",
                    "2.pool.ntp.org"
                ],
                "timezone": "UTC"
            },
            "root": {
                "class": "User",
                "userType": "root",
                "oldPassword": "foo",
                "newPassword": "bar"
            },
            "admin": {
                "class": "User",
                "userType": "regular",
                "password": "asdfjkl",
                "shell": "bash"
            },
            "anotherUser": {
                "class": "User",
                "userType": "regular",
                "password": "foobar",
                "partitionAccess": {
                    "Common": {
                        "role": "guest"
                    }
                }
            },
            "myProvisioning": {
                "class": "Provision",
                "ltm": "nominal"
            },
            "internal": {
                "class": "VLAN",
                "tag": 4093,
                "mtu": 1500,
                "interfaces": [
                    {
                        "name": "1.2",
                        "tagged": true
                    }
                ]
            },
            "internal-self": {
                "class": "SelfIp",
                "address": "10.10.0.100/24",
                "vlan": "internal",
                "allowService": "default",
                "trafficGroup": "traffic-group-local-only"
            },
            "external": {
                "class": "VLAN",
                "tag": 4094,
                "mtu": 1500,
                "interfaces": [
                    {
                        "name": "1.1",
                        "tagged": true
                    }
                ]
            },
            "external-self": {
                "class": "SelfIp",
                "address": "10.20.0.100/24",
                "vlan": "external",
                "allowService": "none",
                "trafficGroup": "traffic-group-local-only"
            },
            "default": {
                "class": "Route",
                "gw": "10.10.0.1",
                "network": "default",
                "mtu": 1500
            }
        }
    }
}
