=== F5Networks/f5-declarative-onboarding/src/schema/1.42.0/base.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/main/src/schema/latest/base.schema.json",
    "title": "F5 BIG-IP Declarative Onboarding base declaration",
    "description": "Top level schema for onboarding a BIG-IP.",
    "type": "object",
    "required": ["schemaVersion", "class"],
    "properties": {
        "schemaVersion": {
            "description": "Version of BIG-IP Declarative Onboarding schema this declaration uses.",
            "type": "string",
            "enum": [
                "1.42.0",
                "1.41.0",
                "1.40.0",
                "1.39.0",
                "1.38.0",
                "1.37.0",
                "1.36.0",
                "1.35.0",
                "1.34.0",
                "1.33.0",
                "1.32.0",
                "1.31.0",
                "1.30.0",
                "1.29.0",
                "1.28.0",
                "1.27.0",
                "1.26.0",
                "1.25.0",
                "1.24.0",
                "1.23.0",
                "1.22.0",
                "1.21.0",
                "1.20.0",
                "1.19.0",
                "1.18.0",
                "1.17.0",
                "1.16.0",
                "1.15.0",
                "1.14.0",
                "1.13.0",
                "1.12.0",
                "1.11.1",
                "1.11.0",
                "1.10.0",
                "1.9.0",
                "1.8.0",
                "1.7.0",
                "1.6.1",
                "1.6.0",
                "1.5.1",
                "1.5.0",
                "1.4.1",
                "1.4.0",
                "1.3.0",
                "1.2.0",
                "1.1.0",
                "1.0.0"
            ]
        },
        "class": {
            "description": "Indicates this JSON document is a Device declaration",
            "type": "string",
            "const": "Device"
        },
        "$schema": {
            "description": "URL of schema against which to validate. Used by validation in your local environment only (via Visual Studio Code, for example)",
            "type": "string",
            "format": "uri"
        },
        "async": {
            "description": "Tells the API to return a 202 HTTP status before processing is complete. User must then poll for status.",
            "type": "boolean",
            "default": false
        },
        "webhook": {
            "description": "URL to post results to",
            "type": "string",
            "format": "uri"
        },
        "label": {
            "description": "Optional friendly name for this declaration",
            "type": "string"
        },
        "Credentials": {
            "description": "Credentials which can be referenced from other parts of the declaration or the remote wrapper.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "username": {
                        "description": "Username of principal authorized to modify configuration of device (may not include the character ':').  NOTE:  this is generally not required to configure 'localhost' because client authentication and authorization precede invocation of DO.  It is also not required for any host if you populate tokens",
                        "type": "string",
                        "pattern": "^[^:]{0,254}$"
                    },
                    "password": {
                        "description": "Password for username account.  This is generally not required to configure 'localhost' and is not required when you populate tokens",
                        "type": "string",
                        "pattern": "^.{0,254}$"
                    },
                    "tokens": {
                        "description": "One or more HTTP headers (each a property, like 'X-F5-Auth-Token': 'ABCABC') you want to send with queries to the device management service as authentication/authorization tokens",
                        "type": "object",
                        "patternProperties": {
                            "^[^\\x00-\\x20:\\x7f-\\xff]{1,254}$": {
                                "type": "string",
                                "pattern": "^[^\\x00-\\x1f\\x7f-\\xff]*$",
                                "maxLength": 8192
                            }
                        },
                        "additionalProperties": false
                    }
                },
                "additionalProperties": false,
                "if": {
                    "required": ["tokens"]
                },
                "then": {
                    "dependencies": {
                        "username": {
                            "not": {}
                        },
                        "password": {
                            "not": {}
                        }
                    }
                },
                "else": {
                    "dependencies": {
                        "tokens": {
                            "not": {}
                        }
                    }
                }
            }
        },
        "Common": {
            "description": "Special tenant Common holds objects other tenants can share",
            "type": "object",
            "required": ["class"],
            "propertyNames": {
                "pattern": "^[A-Za-z][0-9A-Za-z_.-]*$",
                "maxLength": 48
            },
            "properties": {
                "class": {
                    "type": "string",
                    "const": "Tenant"
                },
                "hostname": {
                    "description": "Hostname to set for the device. Note: If you set the hostname as part of the System class, you CANNOT set a hostname in the Common class (they are mutually exclusive).",
                    "type": "string",
                    "format": "hostname"
                }
            },
            "additionalProperties": {
                "properties": {
                    "class": {
                        "enum": [
                            "Analytics",
                            "Authentication",
                            "ConfigSync",
                            "DagGlobals",
                            "DbVariables",
                            "DeviceCertificate",
                            "DeviceGroup",
                            "DeviceTrust",
                            "Disk",
                            "DNS",
                            "DNS_Resolver",
                            "FailoverUnicast",
                            "FailoverMulticast",
                            "HTTPD",
                            "License",
                            "MAC_Masquerade",
                            "ManagementIp",
                            "ManagementIpFirewall",
                            "ManagementRoute",
                            "MirrorIp",
                            "NetAddressList",
                            "NetPortList",
                            "NTP",
                            "PasswordPolicy",
                            "Provision",
                            "RemoteAuthRole",
                            "Route",
                            "RouteDomain",
                            "RouteMap",
                            "RoutingAccessList",
                            "RoutingAsPath",
                            "RoutingPrefixList",
                            "RoutingBGP",
                            "SelfIp",
                            "SnmpAgent",
                            "SnmpCommunity",
                            "SnmpTrapEvents",
                            "SnmpTrapDestination",
                            "SnmpUser",
                            "SSHD",
                            "SyslogRemoteServer",
                            "System",
                            "TrafficControl",
                            "Trunk",
                            "Tunnel",
                            "User",
                            "VLAN",
                            "TrafficGroup",
                            "GSLBGlobals",
                            "GSLBDataCenter",
                            "GSLBServer",
                            "GSLBMonitor",
                            "GSLBProberPool",
                            "FirewallPolicy",
                            "FirewallAddressList",
                            "FirewallPortList",
                            "SecurityAnalytics",
                            "SecurityWaf"
                        ]
                    }
                },
                "allOf": [
                    { "$ref": "system.schema.json#" },
                    { "$ref": "network.schema.json#" },
                    { "$ref": "dsc.schema.json#" },
                    { "$ref": "analytics.schema.json#" },
                    { "$ref": "auth.schema.json#" },
                    { "$ref": "gslb.schema.json#" },
                    { "$ref": "security.schema.json#" }
                ]
            },
            "default": {
                "class": "Tenant"
            }
        },
        "controls": {
            "description": "Options to control configuration process",
            "type": "object",
            "properties": {
                "class": {
                    "type": "string",
                    "const": "Controls"
                },
                "dryRun": {
                    "description": "Boolean that indicates if this declaration will be run as a dry-run. If true, the declaration will NOT make any changes to the system, but will respond with whether or not it would.",
                    "type": "boolean",
                    "default": false
                },
                "trace": {
                    "description": "If true, create a detailed trace of the configuration process for subsequent analysis (default false).  Warning:  trace files may contain sensitive configuration data.",
                    "type": "boolean",
                    "default": false
                },
                "traceResponse": {
                    "description": "If true, the response will contain the trace files.",
                    "type": "boolean",
                    "default": false
                },
                "userAgent": {
                    "description": "User Agent information to include in TEEM report.",
                    "type": "string"
                }
            }
        },
        "result": {
            "description": "Status of current request. This is set by the system.",
            "type": "object",
            "readOnly": true,
            "required": ["class", "code"],
            "properties": {
                "class": {
                    "type": "string",
                    "const": "Result"
                },
                "code": {
                    "description": "Status code.",
                    "type": "string",
                    "enum": ["OK", "ERROR"]
                },
                "message": {
                    "description": "Further detail about the status.",
                    "type": "string"
                }
            }
        }
    },
    "additionalProperties": false
}

=== F5Networks/f5-declarative-onboarding/examples/clusterWithIpAddresses.json
{
    "class": "Device",
    "schemaVersion": "1.0.0",
    "async": true,
    "label": "BIG-IP declaration for declarative onboarding",
    "Common": {
        "class": "Tenant",
        "hostname": "do.example.1",
        "configSync": {
            "class": "ConfigSync",
            "configsyncIp": "10.0.0.1"
        },
        "failoverAddress": {
            "class": "FailoverUnicast",
            "address": "10.0.0.1"
        },
        "trust": {
            "class": "DeviceTrust",
            "localUsername": "exampleUsername",
            "localPassword": "examplePassword",
            "remoteHost": "10.0.0.1",
            "remoteUsername": "exampleUsername",
            "remotePassword": "examplePassword"
        },
        "failoverGroup": {
            "class": "DeviceGroup",
            "type": "sync-failover",
            "members": [
                "10.0.0.1",
                "10.0.0.2"
            ],
            "owner": "/Common/failoverGroup/members/0",
            "autoSync": true,
            "saveOnAutoSync": false,
            "networkFailover": false,
            "fullLoadOnSync": false,
            "asmSync": false
        }
    }
}

=== F5Networks/f5-declarative-onboarding/examples/vxlanTunnel.json
{
    "schemaVersion": "1.25.0",
    "class": "Device",
    "async": true,
    "label": "Configuring System",
    "Common": {
        "class": "Tenant",
        "testTunnel": {
            "class": "Tunnel",
            "description": "none",
            "autoLasthop": "default",
            "mtu": 0,
            "tunnelType": "vxlan",
            "tos": "preserve",
            "usePmtu": true,
            "localAddress": "10.145.0.1",
            "remoteAddress": "239.250.0.2",
            "secondaryAddress": "any6",
            "key": 0,
            "mode": "bidirectional",
            "transparent": false,
            "trafficGroup": "none",
            "defaultsFrom": "vxlan",
            "port": 4789,
            "floodingType": "multicast",
            "encapsulationType": "vxlan"
        }
    }
}

=== F5Networks/f5-declarative-onboarding/examples/userAgent.json
{
    "schemaVersion": "1.13.0",
    "class": "Device",
    "label": "Configuring System",
    "async": true,
    "controls": {
        "class": "Controls",
        "userAgent": "BIG-IQ/7.1 Configured by API"
    },
    "Common": {
        "class": "Tenant",
        "mySystem": {
            "class": "System",
            "hostname": "my.bigip.com",
            "cliInactivityTimeout": 1200,
            "consoleInactivityTimeout": 1200,
            "autoPhonehome": true
        }
    }
}

=== F5Networks/f5-declarative-onboarding/test/functional/bodies/licensing_big_iq.json
{
  "schemaVersion": "1.3.0",
  "class": "Device",
  "async" : true,
  "Common": {
    "class": "Tenant",
    "myLicense" : {
        "class" : "License",
        "licenseType" : "licensePool",
        "bigIqHost" : "10.145.65.76",
        "bigIqUsername" : "admin",
        "bigIqPassword" : "f5netW0rks!",
        "licensePool" : "myLicense",
        "skuKeyword1" : "F5-BIG-MSP-BR-3G",
        "unitOfMeasure" : "hourly",
        "reachable" : true,
        "bigIpUsername" : "admin",
        "bigIpPassword" : "admin"
    }
  }
}

=== F5Networks/f5-declarative-onboarding/test/integration/bodies/network.json
{
    "schemaVersion": "1.0.0",
    "async": true,
    "class": "Device",
    "Common": {
        "class": "Tenant",
        "myVlan": {
            "class": "VLAN",
            "tag": 1234,
            "mtu": 1500,
            "interfaces": [
                {
                    "name": "1.1",
                    "tagged": true
                }
            ]
        },
        "internal": {
            "class": "VLAN",
            "tag": 4094,
            "interfaces": [
                {
                    "name": "1.1",
                    "tagged": false
                }
            ]
        },
        "mySelfIp": {
            "class": "SelfIp",
            "address": "10.148.75.46/24",
            "vlan": "myVlan",
            "allowService": [
                "tcp:80"
            ]
        },
        "myRoute": {
            "class": "Route",
            "gw": "10.148.75.1",
            "network": "10.20.30.0/24",
            "mtu": 1500
        },
        "mySystem": {
            "class": "System",
            "autoPhonehome": false
        }
    }
}

=== F5Networks/f5-declarative-onboarding/test/integration/bodies/onboard.json
{
    "schemaVersion": "1.0.0",
    "class": "Device",
    "async": true,
    "Common": {
        "class": "Tenant",
        "hostname": "f5.example.com",
        "myDns": {
            "class": "DNS",
            "nameServers": [
                "8.8.8.8",
                "2001:4860:4860::8844"
            ],
            "search": [
                "f5.com"
            ]
        },
        "myNtp": {
            "class": "NTP",
            "servers": [
                "0.pool.ntp.org",
                "1.pool.ntp.org"
            ],
            "timezone": "UTC"
        },
        "myProvisioning": {
            "class": "Provision",
            "ltm": "nominal",
            "gtm": "nominal"
        },
        "myVlan": {
            "class": "VLAN",
            "tag": 1234,
            "mtu": 1500,
            "interfaces": [
                {
                    "name": "1.1",
                    "tagged": true
                }
            ],
            "autoLastHop": "enabled"
        },
        "internal": {
            "class": "VLAN",
            "tag": 4094,
            "mtu": 1500,
            "interfaces": [
                {
                    "name": "1.1",
                    "tagged": false
                }
            ],
            "autoLastHop": "disabled"
        },
        "mySelfIp": {
            "class": "SelfIp",
            "address": "10.148.75.46/24",
            "vlan": "myVlan",
            "allowService": [
                "tcp:80"
            ],
            "trafficGroup": "traffic-group-local-only"
        },
        "myRoute": {
            "class": "Route",
            "gw": "10.148.75.1",
            "network": "10.20.30.0/24",
            "mtu": 1500
        },
        "myConfigSync": {
            "class": "ConfigSync",
            "configsyncIp": "/Common/mySelfIp/address"
        },
        "myFailoverUnicast": {
            "class": "FailoverUnicast",
            "addressPorts": [
                {
                    "address": "/Common/mySelfIp/address"
                },
                {
                    "address": "/Common/mySelfIp/address",
                    "port": 126
                }
            ]
        },
        "myFailoverMulticast": {
            "class": "FailoverMulticast",
            "interface": "eth0",
            "address": "224.0.0.100",
            "port": 123
        },
        "mySystem": {
            "class": "System",
            "autoCheck": false,
            "autoPhonehome": false,
            "tmshAuditLog": false,
            "guiAuditLog": true,
            "mcpAuditLog": "verbose"
        },
        "myFailoverGroup": {
            "class": "DeviceGroup",
            "type": "sync-failover",
            "members": [
                "f5.example.com"
            ],
            "owner": "f5.example.com",
            "autoSync": true,
            "saveOnAutoSync": false,
            "networkFailover": true,
            "fullLoadOnSync": false,
            "asmSync": false
        },
        "myTrafficGroup": {
            "class": "TrafficGroup",
            "autoFailbackEnabled": false,
            "autoFailbackTime": 50,
            "failoverMethod": "ha-order",
            "haLoadFactor": 1,
            "haOrder": [
                "f5.example.com"
            ]
        },
        "mySnmpCommunityWithSpecialCharacter": {
            "class": "SnmpCommunity",
            "name": "special!community",
            "ipv6": false,
            "source": "all",
            "oid": ".1",
            "access": "ro"
        },
        "mySnmpCommunityWithoutSpecialCharacter": {
            "class": "SnmpCommunity",
            "ipv6": false,
            "source": "all",
            "oid": ".1",
            "access": "ro"
        }
    }
}

=== F5Networks/f5-declarative-onboarding/examples/routeDomains.json
{
    "schemaVersion": "1.0.0",
    "class": "Device",
    "async": true,
    "Common": {
        "class": "Tenant",
        "hostname": "bigip.example.com",
        "newVlan": {
            "class": "VLAN",
            "interfaces": [
                {
                    "name": "1.0",
                    "tagged": true
                }
            ]
        },
        "Route": {
            "class": "Route",
            "gw": "10.145.127.254",
            "network": "1.2.3.5%100/32"
        },
            "newSelfIp": {
            "class": "SelfIp",
            "address": "1.2.3.6%100/0",
            "vlan": "newVlan"
        },
        "theRouteDomain": {
          "class": "RouteDomain",
          "id": 100,
          "bandWidthControllerPolicy": "bwcPol",
          "connectionLimit": 5432991,
          "flowEvictionPolicy": "default-eviction-policy",
          "ipIntelligencePolicy": "ip-intelligence",
          "enforcedFirewallPolicy": "enforcedPolicy",
          "stagedFirewallPolicy": "stagedPolicy",
          "securityNatPolicy": "securityPolicy",
          "servicePolicy": "servicePolicy",
          "strict": false,
          "routingProtocols": [
            "RIP"
          ],
          "vlans": [
            "newVlan"
          ]
        }
    }
}

=== F5Networks/f5-declarative-onboarding/examples/firewallPolicy.json
{
    "schemaVersion": "1.20.0",
    "class": "Device",
    "async": true,
    "Common": {
        "class": "Tenant",
        "provisioning": {
            "class": "Provision",
            "afm": "nominal"
        },
        "newVlan": {
            "class": "VLAN",
            "interfaces": [
                {
                    "name": "1.1"
                }
            ]
        },
        "selfOne": {
            "class": "SelfIp",
            "address": "192.0.2.10/24",
            "vlan": "/Common/newVlan",
            "enforcedFirewallPolicy": "/Common/firewallPolicy"
        },
        "selfTwo": {
            "class": "SelfIp",
            "address": "192.0.2.20/24",
            "vlan": "/Common/newVlan",
            "stagedFirewallPolicy": "/Common/firewallPolicy"
        },
        "firewallAddressList1": {
            "class": "FirewallAddressList",
            "addresses": ["192.0.2.10", "192.0.2.0/24"]
        },
        "firewallPortList1": {
            "class": "FirewallPortList",
            "ports": [8080, 8888]
        },
        "firewallPortList2": {
            "class": "FirewallPortList",
            "ports": ["8123", "8234", "8300-8350"]
        },
        "firewallPolicy": {
            "class": "FirewallPolicy",
            "label": "Example of all firewall policy properties",
            "remark": "firewall policy description",
            "rules": [
                {
                    "name": "firewallPolicyRule",
                    "label": "Example of all firewall policy rule properties",
                    "remark": "firewall policy rule description",
                    "action": "reject",
                    "protocol": "tcp",
                    "loggingEnabled": true,
                    "source": {
                        "addressLists": [
                            "/Common/firewallAddressList1"
                        ],
                        "portLists": [
                            "/Common/firewallPortList1",
                            "/Common/firewallPortList2"
                        ],
                        "vlans": [
                            "/Common/newVlan"
                        ]
                    },
                    "destination": {
                        "addressLists": [
                            "/Common/firewallAddressList1"
                        ],
                        "portLists": [
                            "/Common/firewallPortList1",
                            "/Common/firewallPortList2"
                        ]
                    }
                }
            ]
        }
    }
}
