=== F5Networks/f5-declarative-onboarding/src/schema/1.42.0/base.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/main/src/schema/latest/base.schema.json",
    "title": "F5 BIG-IP Declarative Onboarding base declaration",
    "description": "Top level schema for onboarding a BIG-IP.",
    "type": "object",
    "required": ["schemaVersion", "class"],
    "properties": {
        "schemaVersion": {
            "description": "Version of BIG-IP Declarative Onboarding schema this declaration uses.",
            "type": "string",
            "enum": [
                "1.42.0",
                "1.41.0",
                "1.40.0",
                "1.39.0",
                "1.38.0",
                "1.37.0",
                "1.36.0",
                "1.35.0",
                "1.34.0",
                "1.33.0",
                "1.32.0",
                "1.31.0",
                "1.30.0",
                "1.29.0",
                "1.28.0",
                "1.27.0",
                "1.26.0",
                "1.25.0",
                "1.24.0",
                "1.23.0",
                "1.22.0",
                "1.21.0",
                "1.20.0",
                "1.19.0",
                "1.18.0",
                "1.17.0",
                "1.16.0",
                "1.15.0",
                "1.14.0",
                "1.13.0",
                "1.12.0",
                "1.11.1",
                "1.11.0",
                "1.10.0",
                "1.9.0",
                "1.8.0",
                "1.7.0",
                "1.6.1",
                "1.6.0",
                "1.5.1",
                "1.5.0",
                "1.4.1",
                "1.4.0",
                "1.3.0",
                "1.2.0",
                "1.1.0",
                "1.0.0"
            ]
        },
        "class": {
            "description": "Indicates this JSON document is a Device declaration",
            "type": "string",
            "const": "Device"
        },
        "$schema": {
            "description": "URL of schema against which to validate. Used by validation in your local environment only (via Visual Studio Code, for example)",
            "type": "string",
            "format": "uri"
        },
        "async": {
            "description": "Tells the API to return a 202 HTTP status before processing is complete. User must then poll for status.",
            "type": "boolean",
            "default": false
        },
        "webhook": {
            "description": "URL to post results to",
            "type": "string",
            "format": "uri"
        },
        "label": {
            "description": "Optional friendly name for this declaration",
            "type": "string"
        },
        "Credentials": {
            "description": "Credentials which can be referenced from other parts of the declaration or the remote wrapper.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "username": {
                        "description": "Username of principal authorized to modify configuration of device (may not include the character ':').  NOTE:  this is generally not required to configure 'localhost' because client authentication and authorization precede invocation of DO.  It is also not required for any host if you populate tokens",
                        "type": "string",
                        "pattern": "^[^:]{0,254}$"
                    },
                    "password": {
                        "description": "Password for username account.  This is generally not required to configure 'localhost' and is not required when you populate tokens",
                        "type": "string",
                        "pattern": "^.{0,254}$"
                    },
                    "tokens": {
                        "description": "One or more HTTP headers (each a property, like 'X-F5-Auth-Token': 'ABCABC') you want to send with queries to the device management service as authentication/authorization tokens",
                        "type": "object",
                        "patternProperties": {
                            "^[^\\x00-\\x20:\\x7f-\\xff]{1,254}$": {
                                "type": "string",
                                "pattern": "^[^\\x00-\\x1f\\x7f-\\xff]*$",
                                "maxLength": 8192
                            }
                        },
                        "additionalProperties": false
                    }
                },
                "additionalProperties": false,
                "if": {
                    "required": ["tokens"]
                },
                "then": {
                    "dependencies": {
                        "username": {
                            "not": {}
                        },
                        "password": {
                            "not": {}
                        }
                    }
                },
                "else": {
                    "dependencies": {
                        "tokens": {
                            "not": {}
                        }
                    }
                }
            }
        },
        "Common": {
            "description": "Special tenant Common holds objects other tenants can share",
            "type": "object",
            "required": ["class"],
            "propertyNames": {
                "pattern": "^[A-Za-z][0-9A-Za-z_.-]*$",
                "maxLength": 48
            },
            "properties": {
                "class": {
                    "type": "string",
                    "const": "Tenant"
                },
                "hostname": {
                    "description": "Hostname to set for the device. Note: If you set the hostname as part of the System class, you CANNOT set a hostname in the Common class (they are mutually exclusive).",
                    "type": "string",
                    "format": "hostname"
                }
            },
            "additionalProperties": {
                "properties": {
                    "class": {
                        "enum": [
                            "Analytics",
                            "Authentication",
                            "ConfigSync",
                            "DagGlobals",
                            "DbVariables",
                            "DeviceCertificate",
                            "DeviceGroup",
                            "DeviceTrust",
                            "Disk",
                            "DNS",
                            "DNS_Resolver",
                            "FailoverUnicast",
                            "FailoverMulticast",
                            "HTTPD",
                            "License",
                            "MAC_Masquerade",
                            "ManagementIp",
                            "ManagementIpFirewall",
                            "ManagementRoute",
                            "MirrorIp",
                            "NetAddressList",
                            "NetPortList",
                            "NTP",
                            "PasswordPolicy",
                            "Provision",
                            "RemoteAuthRole",
                            "Route",
                            "RouteDomain",
                            "RouteMap",
                            "RoutingAccessList",
                            "RoutingAsPath",
                            "RoutingPrefixList",
                            "RoutingBGP",
                            "SelfIp",
                            "SnmpAgent",
                            "SnmpCommunity",
                            "SnmpTrapEvents",
                            "SnmpTrapDestination",
                            "SnmpUser",
                            "SSHD",
                            "SyslogRemoteServer",
                            "System",
                            "TrafficControl",
                            "Trunk",
                            "Tunnel",
                            "User",
                            "VLAN",
                            "TrafficGroup",
                            "GSLBGlobals",
                            "GSLBDataCenter",
                            "GSLBServer",
                            "GSLBMonitor",
                            "GSLBProberPool",
                            "FirewallPolicy",
                            "FirewallAddressList",
                            "FirewallPortList",
                            "SecurityAnalytics",
                            "SecurityWaf"
                        ]
                    }
                },
                "allOf": [
                    { "$ref": "system.schema.json#" },
                    { "$ref": "network.schema.json#" },
                    { "$ref": "dsc.schema.json#" },
                    { "$ref": "analytics.schema.json#" },
                    { "$ref": "auth.schema.json#" },
                    { "$ref": "gslb.schema.json#" },
                    { "$ref": "security.schema.json#" }
                ]
            },
            "default": {
                "class": "Tenant"
            }
        },
        "controls": {
            "description": "Options to control configuration process",
            "type": "object",
            "properties": {
                "class": {
                    "type": "string",
                    "const": "Controls"
                },
                "dryRun": {
                    "description": "Boolean that indicates if this declaration will be run as a dry-run. If true, the declaration will NOT make any changes to the system, but will respond with whether or not it would.",
                    "type": "boolean",
                    "default": false
                },
                "trace": {
                    "description": "If true, create a detailed trace of the configuration process for subsequent analysis (default false).  Warning:  trace files may contain sensitive configuration data.",
                    "type": "boolean",
                    "default": false
                },
                "traceResponse": {
                    "description": "If true, the response will contain the trace files.",
                    "type": "boolean",
                    "default": false
                },
                "userAgent": {
                    "description": "User Agent information to include in TEEM report.",
                    "type": "string"
                }
            }
        },
        "result": {
            "description": "Status of current request. This is set by the system.",
            "type": "object",
            "readOnly": true,
            "required": ["class", "code"],
            "properties": {
                "class": {
                    "type": "string",
                    "const": "Result"
                },
                "code": {
                    "description": "Status code.",
                    "type": "string",
                    "enum": ["OK", "ERROR"]
                },
                "message": {
                    "description": "Further detail about the status.",
                    "type": "string"
                }
            }
        }
    },
    "additionalProperties": false
}

=== F5Networks/f5-declarative-onboarding/examples/managementIpFirewall.json
{
    "schemaVersion": "1.24.0",
    "class": "Device",
    "async": true,
    "Common": {
        "class": "Tenant",
        "firewallAddressList1": {
            "class": "FirewallAddressList",
            "addresses": ["192.0.2.10", "192.1.2.0/24"]
        },
        "firewallPortList1": {
            "class": "FirewallPortList",
            "ports": [8080, 8888]
        },
        "firewallPortList2": {
            "class": "FirewallPortList",
            "ports": ["8123", "8234", "8300-8350"]
        },
        "managementIpFirewall": {
            "class": "ManagementIpFirewall",
            "label": "Example of all management IP firewall properties",
            "remark": "management IP firewall description",
            "rules": [
                {
                    "name": "firewallRule",
                    "label": "Example of all firewall rule properties",
                    "remark": "firewall rule description",
                    "action": "reject",
                    "protocol": "tcp",
                    "loggingEnabled": true,
                    "source": {
                        "addressLists": [
                            "/Common/firewallAddressList1"
                        ],
                        "portLists": [
                            "/Common/firewallPortList1",
                            "/Common/firewallPortList2"
                        ]
                    },
                    "destination": {
                        "addressLists": [
                            "/Common/firewallAddressList1"
                        ],
                        "portLists": [
                            "/Common/firewallPortList1",
                            "/Common/firewallPortList2"
                        ]
                    }
                }
            ]
        }
    }
}

=== F5Networks/f5-declarative-onboarding/examples/macMasquerade.json
{
    "schemaVersion": "1.13.0",
    "class": "Device",
    "async": false,
    "Common": {
        "class": "Tenant",
        "myMac": {
            "class": "MAC_Masquerade",
            "source": {
                "interface": "1.1"
            },
            "trafficGroup": "traffic-group-1"
        }
    }
}

=== F5Networks/f5-declarative-onboarding/test/functional/bodies/auth.json
{
    "schemaVersion": "1.0.0",
    "async" : true,
    "class": "Device",
    "Common": {
      "class": "Tenant",
        "myAuth": {
            "class": "Authentication",
            "enabledSourceType": "radius",
            "fallback": true,
            "radius": {
                "serviceType": "call-check",
                "servers": {
                    "primary": {
                        "server": "1.2.3.4",
                        "port": 1811,
                        "secret": "shhhhhh"
                    },
                    "secondary": {
                        "server": "my.second.server",
                        "secret": "dontTell",
                        "port": 1888
                    }
                }
            },
            "ldap": {
                "bindDn": "searchingName",
                "bindPassword": "shhhhhh",
                "bindTimeout": 40,
                "checkBindPassword": true,
                "checkRemoteRole": true,
                "filter": "filter",
                "groupDn": "groupName",
                "groupMemberAttribute": "attribute",
                "idleTimeout": 20,
                "ignoreAuthInfoUnavailable": true,
                "ignoreUnknownUser": true,
                "loginAttribute": "attributeToLogin",
                "port": 654,
                "searchScope": "base",
                "searchBaseDn": "searchName",
                "searchTimeout": 687,
                "servers": [
                    "my.host.com",
                    "1.2.3.4",
                    "FE80:0000:0000:0000:0202:B3FF:FE1E:8329"
                ],
                "userTemplate": "uid=%s,ou=people,dc=siterequest,dc=com",
                "version": 2
            }
        }
    }
}

=== F5Networks/f5-declarative-onboarding/examples/managementIp.json
{
    "schemaVersion": "1.23.0",
    "class": "Device",
	"async": true,
    "Common": {
    	"class": "Tenant",
        "hostname": "bigip.example.com",
        "myManagementIp": {
            "class": "ManagementIp",
            "address": "10.10.10.1/18",
            "remark": "this is my management ip"
        }
    }
}

=== F5Networks/f5-declarative-onboarding/examples/vlanAutoLastHop.json
{
    "schemaVersion": "1.22.0",
    "class": "Device",
    "async": true,
    "Common": {
        "class": "Tenant",
        "external": {
            "class": "VLAN",
            "tag": 4094,
            "mtu": 1500,
            "interfaces": [
                {
                    "name": "1.1",
                    "tagged": true
                }
            ],
            "autoLastHop": "disabled"
        },
        "internal": {
            "class": "VLAN",
            "tag": 4093,
            "mtu": 1500,
            "interfaces": [
                {
                    "name": "1.2",
                    "tagged": true
                }
            ],
            "autoLastHop": "default"
        }
    }
}

=== F5Networks/f5-declarative-onboarding/examples/vlanCmpHash.json
{
    "schemaVersion": "1.7.0",
    "class": "Device",
    "async": true,
    "webhook": "https://example.com/myHook",
    "Common": {
        "class": "Tenant",
        "external": {
            "class": "VLAN",
            "tag": 4094,
            "mtu": 1500,
            "interfaces": [
                {
                    "name": "1.1",
                    "tagged": true
                }
            ],
            "cmpHash": "src-ip"
        }
    }
}

=== F5Networks/f5-declarative-onboarding/test/functional/bodies/onboard.json
{
  "schemaVersion": "1.0.0",
  "class": "Device",
  "async": true,
    "Common": {
      "class": "Tenant",
        "hostname": "f5.example.com",
        "myDns": {
            "class": "DNS",
            "nameServers": [
              "8.8.8.8",
                "2001:4860:4860::8844"
            ],
            "search": [
                "f5.com"
            ]
        },
        "myNtp": {
            "class": "NTP",
            "servers": [
              "0.pool.ntp.org",
                "1.pool.ntp.org"
            ],
            "timezone": "UTC"
        },
        "myProvisioning": {
          "class": "Provision",
          "ltm": "nominal"
        },
        "admin": {
            "class": "User",
            "userType": "regular",
            "password": "admin",
            "shell": "bash"
        },
        "anotherUser": {
            "class": "User",
            "userType": "regular",
            "password": "admin",
            "partitionAccess": {
                "Common": {
                    "role": "guest"
                }
            }
        },
        "myVlan": {
            "class": "VLAN",
            "tag": 1234,
            "mtu": 1500,
            "interfaces": [
                {
                    "name": "1.1",
                    "tagged": true
                }
            ]
        },
        "mySelfIp": {
            "class": "SelfIp",
            "address": "10.148.75.46/24",
            "vlan": "myVlan",
            "allowService": ["tcp:80"],
            "trafficGroup": "traffic-group-local-only"
        },
        "myRoute": {
            "class": "Route",
            "gw": "10.148.75.1",
            "network": "default",
            "mtu": 1500
        }
    }
}

=== F5Networks/f5-declarative-onboarding/examples/user.json
{
    "schemaVersion": "1.0.0",
    "class": "Device",
    "async": true,
    "webhook": "https://example.com/myHook",
    "label": "user class",
    "Common": {
        "class": "Tenant",
        "root": {
            "class": "User",
            "userType": "root",
            "oldPassword": "foo",
            "newPassword": "bar"
        },
        "admin": {
            "class": "User",
            "userType": "regular",
            "password": "asdfjkl",
            "shell": "bash"
        },
        "guestUser": {
            "class": "User",
            "userType": "regular",
            "password": "foobar",
            "partitionAccess": {
                "Common": {
                    "role": "guest"
                }
            }
        },
        "anotherUser": {
            "class": "User",
            "userType": "regular",
            "password": "foobar",
            "shell": "none",
            "partitionAccess": {
                "all-partitions": {
                    "role": "guest"
                }
            },
            "forceInitialPasswordChange": false
        }
    }
}
