=== F5Networks/f5-declarative-onboarding/schema/base.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/F5Networks/f5-decon/master/schema/base.schema.json",
    "title": "F5 Declarative Onboarding base declaration",
    "description": "Top level schema for onboarding a BIG-IP.",
    "type": "object",
    "required": ["schemaVersion"],
    "properties": {
        "schemaVersion": {
            "description": "Version of Declarative Onboarding schema this declaration uses.",
            "type": "string",
            "$comment": "IMPORTANT: In enum array, please put current schema version first, oldest-supported version last.  Keep enum array sorted most-recent-first.",
            "enum": ["0.1.0"]
        },
        "class": {
            "description": "Indicates this JSON document is a Device declaration",
            "type": "string",
            "const": "Device",
            "default": "Device"
        },
        "label": {
            "description": "Optional friendly name for this declaration",
            "type": "string"
        },
        "Common": {
            "description": "Special tenant Common holds objects other tenants can share",
            "type": "object",
            "properties": {
                "class": {
                    "type": "string",
                    "const": "Tenant",
                    "default": "Tenant"
                }
            },
            "additionalProperties": {
                "$ref": "system.schema.json"
            },
            "propertyNames": { "pattern": "^[A-Za-z][0-9A-Za-z_]{0,47}$" }
        },
        "result": {
            "description": "Status of current request. This is set by the system.",
            "type": "object",
            "readOnly": true,
            "required": ["class", "code"],
            "properties": {
                "class": {
                    "type": "string",
                    "const": "Result"
                },
                "code": {
                    "description": "Status code.",
                    "type": "string",
                    "readOnly": true,
                    "enum": ["OK", "ERROR"]
                },
                "message": {
                    "description": "Further detail about the status.",
                    "type": "string",
                    "readOnly": true
                }
            }
        }
    }
}

=== F5Networks/f5-declarative-onboarding/docs/examples/example_01.json
{
    "schemaVersion": "0.1.0",
    "class": "Device",
    "label": "my BIG-IP declaration for declarative onboarding",
    "Common": {
        "class": "Tenant",
        "hostname": "bigip.example.com",
        "myLicense": {
            "class": "License",
            "licenseType": "regKey",
            "regKey": "AAAAA-BBBBB-CCCCC-DDDDD-EEEEEEE"
        },
        "myProvisioning": {
            "class": "Provision",
            "ltm": "nominal"
        },
        "myDns": {
            "class": "DNS",
            "nameServers": [
                "8.8.8.8",
                "2001:4860:4860::8844"
            ],
            "search": [
                "f5.com"
            ]
        },
        "myNtp": {
            "class": "NTP",
            "servers": [
                "0.pool.ntp.org",
                "1.pool.ntp.org"
            ],
            "timezone": "UTC"
        },
        "root": {
            "class": "User",
            "userType": "root",
            "oldPassword": "default",
            "newPassword": "myNewPass1word"
        },
        "admin": {
            "class": "User",
            "userType": "regular",
            "password": "asdfjkl",
            "shell": "bash"
        },
        "anotherUser": {
            "class": "User",
            "userType": "regular",
            "password": "foobar",
            "partitionAccess": {
                "Common": {
                    "role": "guest"
                }
            }
        },
        "myVlan": {
            "class": "VLAN",
            "tag": 1234,
            "mtu": 1500,
            "interfaces": [
                {
                    "name": "1.1",
                    "tagged": true
                }
            ]
        },
        "mySelfIp": {
            "class": "SelfIp",
            "address": "1.2.3.4/24",
            "vlan": "myVlan",
            "allowService": "all",
            "floating": true
        },
        "myRoute": {
            "class": "Route",
            "gw": "10.1.20.1",
            "network": "default",
            "mtu": 0
        }
    }
}
